apiVersion: apps/v1
kind: Deployment
metadata:
  name: extraction-service
  namespace: file-system
  labels:
    app: extraction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: extraction-service
  template:
    metadata:
      labels:
        app: extraction-service
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 2; done;']
      - name: wait-for-file-service
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z file-service 8001; do echo waiting for file-service; sleep 2; done;']
      containers:
      - name: extraction-service
        image: file-system:latest
        command: ["python", "-m", "uvicorn", "src.extraction_service.app:app", "--host", "0.0.0.0", "--port", "8002"]
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: file-system-config
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://file_system_user:$(DB_PASSWORD)@postgres-service:5432/file_system_db"
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@redis-service:6379/0"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        volumeMounts:
        - name: file-storage
          mountPath: /app/storage
          readOnly: true
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: file-storage-pvc
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: extraction-service
  namespace: file-system
  labels:
    app: extraction-service
spec:
  selector:
    app: extraction-service
  ports:
  - port: 8002
    targetPort: 8002
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: extraction-service-hpa
  namespace: file-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: extraction-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
