"""empty message

Revision ID: aea86094dad1
Revises: 
Create Date: 2025-09-30 16:39:18.476645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aea86094dad1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cf_filerepo_file_created_at'), table_name='cf_filerepo_file')
    op.drop_index(op.f('idx_cf_filerepo_file_tag'), table_name='cf_filerepo_file')
    op.drop_index(op.f('idx_cf_filerepo_file_tenant_id'), table_name='cf_filerepo_file')
    op.drop_table('cf_filerepo_file')
    op.drop_table('cf_filerepo_tenant_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cf_filerepo_tenant_config',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name='cf_filerepo_tenant_config_pkey'),
    sa.UniqueConstraint('tenant_code', name='cf_filerepo_tenant_config_tenant_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('cf_filerepo_file',
    sa.Column('file_id', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['cf_filerepo_tenant_config.tenant_id'], name=op.f('cf_filerepo_file_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', name=op.f('cf_filerepo_file_pkey')),
    sa.UniqueConstraint('file_path', name=op.f('cf_filerepo_file_file_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_cf_filerepo_file_tenant_id'), 'cf_filerepo_file', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_cf_filerepo_file_tag'), 'cf_filerepo_file', ['tag'], unique=False)
    op.create_index(op.f('idx_cf_filerepo_file_created_at'), 'cf_filerepo_file', ['created_at'], unique=False)
    # ### end Alembic commands ###
